import { useState } from "react";

import Head from "next/head";
import Form from "../components/Form";
import Result from "../components/Result";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [value, setValue] = useState(0); //valor input
  console.log('value--', value)

  return (
    <div className={styles.container}>
      <Head>
        <title>Sngular PT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/sngular-logo.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          className={styles.logoSngular}
          src="/Sngular_Logo.jpeg"
          alt="sngular Logo"
          width={500}
          height={116}
        />
        <h1 className={styles.title}>
          The best way to predict the future is to invent it.
        </h1>
        <Form sendData={setValue}/>
        <Result valueResult={value}/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/RubSDev/sngular_pt
          target="_blank"
          rel="noopener noreferrer"
        >
          Creado por RubSDev{" "}
          <span className={styles.logo}>
            <Image
              src="/github.png"
              alt="sngular Logo"
              width={16}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
